### ISSUE TITLE
Make it work with peewee 3.0

### ISSUE THREAD

**Issue by timster** [timster/peewee-moves#1]
There are definitely some changes needed. I will try to figure it out this weekend.

**Comment by PeRDy** [comment]
Hey !

First of all thanks for your great work on that. I've been playing around a bit with this lib and I'm trying to build something on top of it [apistar-peewee-orm](https://github.com/PeRDy/apistar-peewee-orm) but I just found it doesn't work with Peewee 3.0 yet. Have you any plans to make it soon? Can I help you in some way?

Thanks !

**Comment by timster** [comment]
Hello! I have not had a chance to look at this at all, unfortunately. If you want to help out, that would be amazing.

I would probably start by installing peewee > 3.0.0 and then running the test suite for this project:

1. clone this repo
2. run `pip install -r requirements-test.txt`
3. run `pip install peewee -U` to get latest version
3. run `pytest`

That will throw a bunch of errors since a lot of the peewee API has changed. This page documents the things that changed in 3.x:

http://docs.peewee-orm.com/en/latest/peewee/changes.html

So in cases where we are using `db_table`, it should now use `table_name`.

I think it might be easiest to make this a new major version and drop support for peewee < 3. That way we don't need to worry about supporting both versions of peewee.

So then it's just a matter of finding all instances of things that changed in the peewee API, making sure it works with the new API and the test suite passes.

**Comment by timster** [comment]
I have pushed 2.0.0 to pypy which now has support for peewee 3 (and drops support for peewee 2).

https://pypi.org/project/peewee-moves/

Huge thanks to @arnulfojr for basically doing all the work :)
