### ISSUE TITLE
New release to include the fakemodel_* index naming fix?

### ISSUE THREAD

**Issue by zalmanu** [timster/peewee-moves#12]
We've bumped into the same problem that was fixed in https://github.com/timster/peewee-moves/pull/9 but the latest release on PyPI doesn't include the fix. Could you make a new release so that the fix is included?

Thanks for your work. The lib has turned out to be very useful so far.

**Comment by timster** [comment]
Yeah I will push a new release soon. Stay tuned.

**Comment by amohar** [comment]
I'm having the same problem. Any updates on the new version upgrade? Thanks!

**Comment by timster** [comment]
Oh my goodness. I'm in the middle of a move and I forgot about this. I'm totally sorry.

2.0.2 has been pushed that should have the fix. Let me know if it works for you.

https://pypi.org/project/peewee-moves/2.0.2/
