### ISSUE TITLE
Foreign-key field nullable not handled correctly

### ISSUE THREAD

**Issue by davidluca** [timster/peewee-moves#13]
When trying to `create` a migration for a nullable `ForeignKeyField` , `null=True` does not appear in migration.

Eg:
- model:
    `purchase_request = ForeignKeyField(null=True, model=JumpPurchaseRequest, backref='jump_event')`

- migration:
    `table.foreign_key('AUTO', 'purchase_request_id', on_delete=None, on_update=None, references='jump_purchase_request.id')`

Thank you!

**Comment by timster** [comment]
I fixed this in 2.0.3.

Release: https://pypi.org/project/peewee-moves/2.0.3/

Code fix is here: https://github.com/timster/peewee-moves/commit/d8ee7d294795db03a5ddd2acbcef3a46580ac342

Please let me know if it works for you.
