### ISSUE TITLE
Feature: Fake migration

### ISSUE THREAD

**Issue by AMecea** [timster/peewee-moves#14]
Hi @timster, thank you for your work, I really appreciate it!

We would like to include peewee-moves in our [framework](https://github.com/colibris-framework/colibris) but we need a method to fake apply the migration in order to provide an easy way for the users to do the upgrade.

Please let me know what do you think and I would be glad to contribute with this feature.

Thank you!

**Comment by timster** [comment]
What do you mean by "fake apply"?

I'd be glad to add whatever feature is necessary, but I just want to make sure I understand what you need.

**Comment by AMecea** [comment]
I mean to mark the migration applied but without doing any real changes to the database tables. It's like [Django `migrate --fake`](https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-migrate-fake)

**Comment by timster** [comment]
Gotcha. I pushed commits to add a `--fake` flag to upgrade and downgrade operations. I added info to the docs as well.

Let me know what you think

I haven't pushed to pypi, but this will go up as version 2.0.4

Also, I haven't used colibris before, but if there are any other changes that would make it easier to use together (like I have done for Flask integration), let me know and I'd be glad to add them.

**Comment by AMecea** [comment]
Thank you very much @timster, it's perfect this is what we needed, I will let you know if we need anything else.

I have a suggestion, I think it's ok to bump the minor version (2.1.0) because you added a new feature :smile:

Thank you!

**Comment by timster** [comment]
I have published 2.1.0

https://pypi.org/project/peewee-moves/

**Comment by AMecea** [comment]
Thanks a lot @timster! I will close this now!
