### ISSUE TITLE
Click Package Requirement

### ISSUE THREAD

**Issue by mattstrayer** [timster/peewee-moves#2]
Hi!

I'm using peewee-moves without Flask and upon importing the `DatabaseManager`, I'm getting an error about the missing package, `Click` at line 907. 

Happy to put in a PR to add `Click` into the `requirements.txt`, but I wanted to get some feedback from @timster before doing so. 

Thanks!

**Comment by timster** [comment]
Sounds good. PR definitely welcome. Should probably pin to `click>=2.0` since that's what flask uses. That way there would be no conflict.

**Comment by timster** [comment]
Thanks. I pushed 1.7.3 to pypi so you should be able to get it from there now.
