### ISSUE TITLE
Support for peewee.TimestampField

### ISSUE THREAD

**Issue by dougthor42** [timster/peewee-moves#8]
Looks like the `peewee.TimestampField` isn't handled properly when creating migrations.

### Model:
```python
from peewee import Model
from peewee import TimestampField
class Data(Model):
    timestamp = TimestampField(utc=True)
    class Meta(object):
        database = db
```

### Resulting migration:
```python
def upgrade(migrator):
    with migrator.create_table('data') as table:
        table.primary_key('id')
        table.timestamp('timestamp')
```

### Correct migration:
[`peewee.TimestampField` gets converted to `int`](http://docs.peewee-orm.com/en/latest/peewee/models.html#field-types-table) for all database backends.
```python
def upgrade(migrator):
    with migrator.create_table('data') as table:
        table.primary_key('id')
        table.int('timestamp')
```

## Resolution

I see you already have the [mapping implemented](https://github.com/timster/peewee-moves/blob/0161a2e0c03afede93533e4c3b449bdd6e52fc97/peewee_moves.py#L53), but either the target is wrong (change to `peewee.TimestampField: 'int',`) or the target is not created (`TableCreator.timestamp`).

**Comment by timster** [comment]
You're right. Should be a fairly easy fix. I will try to get to it this week.

**Comment by dougthor42** [comment]
Yeah looks like it's working correctly. Thanks a bunch!
